### ISSUE TITLE
OneTimePassword must contain at least 8 characters, during upgrade

### ISSUE THREAD

**Issue by vbabiy** [apppackio/apppack#23] opened 2021-04-26 15:55 UTC
```
apppack upgrade database apppack
...
✖ ValidationError: Parameter 'OneTimePassword' must contain at least 8 characters
	status code: 400, request id: 6c78ef8d-c2e5-4594-a756-0592b1986fe1
```

**Comment by ipmb** [comment] 2021-04-27 00:11
Dupe of #19

**Closed by ipmb** 2021-04-27 00:11 UTC
